name: akashic_records
description: A novel reader application.
publish_to: "none"

version: 1.1.16+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.3.0
  html: ^0.15.5
  webview_flutter: ^4.10.0
  webview_flutter_plus: ^0.4.13
  flutter_html: ^3.0.0
  shared_preferences: ^2.5.2
  intl: ^0.19.0
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  webdriver: ^3.1.0
  permission_handler: ^11.4.0
  cookie_jar: ^4.0.8
  dio: ^5.8.0+1
  dio_cookie_manager: ^3.2.0
  path_provider: ^2.1.5
  flutter_colorpicker: ^1.1.0
  async: ^2.12.0
  url_launcher: ^6.3.1
  provider: ^6.1.2
  scrollable_positioned_list: ^0.3.8
  package_info_plus: ^8.3.0
  flutter_markdown: ^0.7.7
  flutter_localizations:
    sdk: flutter
  gen_i18n: ^1.0.3
  flutter_code_editor: ^0.3.3
  google_fonts: ^6.2.1
  highlight: ^0.7.0
  google_nav_bar: ^5.0.7
  flutter_advanced_drawer: ^1.4.0
  uuid: ^4.5.1
  rxdart: ^0.28.0
  hive_flutter: ^1.1.0
  firebase_analytics: ^11.4.5
  flutter_epub_viewer: ^1.2.1
  file_picker: ^10.1.2
  epubx: ^4.0.0
  jsf: ^0.6.1
  battery_plus: ^6.2.1
  wakelock_plus: ^1.3.2
  traffic_stats: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/i18n/locale/
    - lib/assets/js/epubjs.js
